### ISSUE TITLE
Add scilis, signaculum, etc to r-universe

### ISSUE THREAD

**Issue by jrosell** [devOpifex/signaculum#1]
In order to be able to make deployments niecer, add devOpifex/signaculum to r-universe. Here is how (it seems like your org only have one package selected) https://github.com/r-universe-org/help?tab=readme-ov-file#how-to-setup-your-personal-universe

**Comment by JohnCoene** [comment]
Sure, good idea, see [devopifex.r-universe.dev/builds](https://devopifex.r-universe.dev/builds)
